language: java

jdk:
  - openjdk14

services:
    - postgresql

before_install:
    - psql -c 'create database fullstack_auth;' -U postgres


sudo: false

env:
  global:
    - CODECOV_TOKEN="5be5fd75-d674-4138-be6f-01de1bbd283a"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - kirshaav@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always
